Repository CodyMichaelSimmons/EmployeeWellnessProject, pull requests merged in 2018-10, with the labels that each got.

#20 Update color
  .gitignore
  public/stylesheets/style.css
  public/stylesheets/style.css.map
  public/stylesheets/utilities/_variables.sass
Labels: Interface

#21 Develop
  .gitignore
  package.json
  public/javascripts/anime.min.js
  public/javascripts/autocomplete.js
  public/javascripts/bin/materialize.js
  public/javascripts/bin/materialize.min.js
  public/javascripts/buttons.js
  public/javascripts/cards.js
  public/javascripts/carousel.js
  public/javascripts/cash.js
  public/javascripts/characterCounter.js
  public/javascripts/chips.js
  public/javascripts/collapsible.js
  public/javascripts/component.js
  public/javascripts/datepicker.js
  public/javascripts/dropdown.js
  public/javascripts/forms.js
  public/javascripts/global.js
  public/javascripts/materialbox.js
  public/javascripts/modal.js
  public/javascripts/parallax.js
  public/javascripts/pushpin.js
  public/javascripts/range.js
  public/javascripts/scrollspy.js
  public/javascripts/select.js
  public/javascripts/sidenav.js
  public/javascripts/slider.js
  public/javascripts/tabs.js
  public/javascripts/tapTarget.js
  public/javascripts/timepicker.js
  public/javascripts/toasts.js
  public/javascripts/tooltip.js
  public/javascripts/waves.js
  public/stylesheets/style.css
  public/stylesheets/style.css.map
  public/stylesheets/utilities/_variables.sass
  routes/index.js
  routes/utils.js
  spec/jasmine_spec.js
  spec/support/jasmine.json
Labels: API / External, Backend, Bug, Interface, Tests

#22 Music integration
  routes/index.js
  routes/utils.js
  views/index.pug
Labels: API / External, Backend, Bug, Interface

#23 Adds Music Functionality
  routes/index.js
  routes/utils.js
  views/index.pug
Labels: API / External, Feature

#25 Adds music controls and basic formatting
  public/stylesheets/style.sass
  views/index.pug
Labels: Feature, Interface

#33 adding documentation
  README.md
  app.js
  out/fonts/OpenSans-Bold-webfont.eot
  out/fonts/OpenSans-Bold-webfont.svg
  out/fonts/OpenSans-Bold-webfont.woff
  out/fonts/OpenSans-BoldItalic-webfont.eot
  out/fonts/OpenSans-BoldItalic-webfont.svg
  out/fonts/OpenSans-BoldItalic-webfont.woff
  out/fonts/OpenSans-Italic-webfont.eot
  out/fonts/OpenSans-Italic-webfont.svg
  out/fonts/OpenSans-Italic-webfont.woff
  out/fonts/OpenSans-Light-webfont.eot
  out/fonts/OpenSans-Light-webfont.svg
  out/fonts/OpenSans-Light-webfont.woff
  out/fonts/OpenSans-LightItalic-webfont.eot
  out/fonts/OpenSans-LightItalic-webfont.svg
  out/fonts/OpenSans-LightItalic-webfont.woff
  out/fonts/OpenSans-Regular-webfont.eot
  out/fonts/OpenSans-Regular-webfont.svg
  out/fonts/OpenSans-Regular-webfont.woff
  out/global.html
  out/index.html
  out/module-utils.html
  out/scripts/linenumber.js
  out/scripts/prettify/Apache-License-2.0.txt
  out/scripts/prettify/lang-css.js
  out/scripts/prettify/prettify.js
  package.json
  routes/index.js
  routes/utils.js
Labels: docs

#35 Alters app branding to OfficeBeatZ.
  public/images/android-chrome-192x192.png
  public/images/android-chrome-512x512.png
  public/images/apple-touch-icon.png
  public/images/browserconfig.xml
  public/images/favicon-16x16.png
  public/images/favicon-32x32.png
  public/images/favicon.ico
  public/images/mstile-144x144.png
  public/images/mstile-150x150.png
  public/images/safari-pinned-tab.svg
  public/images/site.webmanifest
  routes/index.js
  views/layout.pug
Labels: Interface

#36 added sharing generation and created endpoint for looping requests
  routes/index.js
  routes/utils.js
Labels: API / External, Backend, Feature

#37 Interface Overhaul
  app.js
  public/images/officebeatz-banner.png
  public/javascripts/main.js
  public/stylesheets/style.sass
  views/index.pug
  views/layout.pug
Labels: Feature, Interface

#38 Runs ESLint
  app.js
  public/javascripts/main.js
  routes/index.js
  routes/users.js
  routes/utils.js
  spec/jasmine_spec.js
Labels: docs

#39 Version Update
  README.md
  app.js
  out/fonts/OpenSans-Bold-webfont.eot
  out/fonts/OpenSans-Bold-webfont.svg
  out/fonts/OpenSans-Bold-webfont.woff
  out/fonts/OpenSans-BoldItalic-webfont.eot
  out/fonts/OpenSans-BoldItalic-webfont.svg
  out/fonts/OpenSans-BoldItalic-webfont.woff
  out/fonts/OpenSans-Italic-webfont.eot
  out/fonts/OpenSans-Italic-webfont.svg
  out/fonts/OpenSans-Italic-webfont.woff
  out/fonts/OpenSans-Light-webfont.eot
  out/fonts/OpenSans-Light-webfont.svg
  out/fonts/OpenSans-Light-webfont.woff
  out/fonts/OpenSans-LightItalic-webfont.eot
  out/fonts/OpenSans-LightItalic-webfont.svg
  out/fonts/OpenSans-LightItalic-webfont.woff
  out/fonts/OpenSans-Regular-webfont.eot
  out/fonts/OpenSans-Regular-webfont.svg
  out/fonts/OpenSans-Regular-webfont.woff
  out/global.html
  out/index.html
  out/module-utils.html
  out/scripts/linenumber.js
  out/scripts/prettify/Apache-License-2.0.txt
  out/scripts/prettify/lang-css.js
  out/scripts/prettify/prettify.js
  package.json
  public/images/android-chrome-192x192.png
  public/images/android-chrome-512x512.png
  public/images/apple-touch-icon.png
  public/images/browserconfig.xml
  public/images/favicon-16x16.png
  public/images/favicon-32x32.png
  public/images/favicon.ico
  public/images/mstile-144x144.png
  public/images/mstile-150x150.png
  public/images/officebeatz-banner.png
  public/images/safari-pinned-tab.svg
  public/images/site.webmanifest
  public/javascripts/main.js
  public/stylesheets/style.sass
  routes/index.js
  routes/users.js
  routes/utils.js
  spec/jasmine_spec.js
  views/index.pug
  views/layout.pug
Labels: API / External, Backend, Feature, Interface, docs

#40 Base Looping Functionality
  public/javascripts/main.js
  routes/index.js
Labels: API / External, Backend, Feature

#41 Custom Interval Selection
  public/javascripts/main.js
  public/stylesheets/components/_variables.scss
  public/stylesheets/style.sass
  views/index.pug
Labels: Feature, Interface

#42 Merges Develop
  public/javascripts/main.js
  public/stylesheets/components/_variables.scss
  public/stylesheets/style.sass
  routes/index.js
  views/index.pug
Labels: API / External, Backend, Feature, Interface

#44 Updates outdated dependencies.
  package.json
Labels: Dependencies

#45 Abstracts Pug components into their own files.
  public/javascripts/main.js
  views/advanced-settings-tab.pug
  views/footer.pug
  views/getting-started-tab.pug
  views/header.pug
  views/home-tab.pug
  views/index.pug
  views/interval-form.pug
  views/scripts.pug
Labels: Interface

#46 Version Update
  package.json
  public/javascripts/main.js
  views/advanced-settings-tab.pug
  views/footer.pug
  views/getting-started-tab.pug
  views/header.pug
  views/home-tab.pug
  views/index.pug
  views/interval-form.pug
  views/scripts.pug
Labels: Dependencies, Interface
