Repository CodyMichaelSimmons/EmployeeWellnessProject, pull requests merged in 2018-11, with the labels that each got.

#53 Interval Interface Feedback
  public/javascripts/main.js
  public/stylesheets/style.sass
  views/interval-form.pug
Labels: Interface

#54 updated getting started info
  public/stylesheets/style.sass
  views/getting-started-tab.pug
Labels: Interface, docs

#55 Skip button
  public/javascripts/main.js
  views/header.pug
Labels: Feature, Interface

#59 Volume Control
  public/javascripts/main.js
  public/stylesheets/style.sass
  views/header.pug
Labels: Feature, Interface

#61 Interval Tests
  public/javascripts/main.js
  spec/interval_spec.js
Labels: Tests

#62 Id3 backend
  config.json
  package.json
  routes/index.js
  routes/utils.js
Labels: API / External, Backend, Feature
