Repository CodyMichaelSimmons/EmployeeWellnessProject, pull requests merged in 2018-09, with the labels that each got.

#9 Sets accent variables, Open Sans font, and alters title.
  public/stylesheets/style.css
  public/stylesheets/style.css.map
  public/stylesheets/style.sass
  public/stylesheets/utilities/_variables.sass
  routes/index.js
  views/index.pug
  views/layout.pug
Labels: Interface

#11 Imports MaterializeCSS
  public/stylesheets/components/_badges.scss
  public/stylesheets/components/_buttons.scss
  public/stylesheets/components/_cards.scss
  public/stylesheets/components/_carousel.scss
  public/stylesheets/components/_chips.scss
  public/stylesheets/components/_collapsible.scss
  public/stylesheets/components/_color-classes.scss
  public/stylesheets/components/_color-variables.scss
  public/stylesheets/components/_datepicker.scss
  public/stylesheets/components/_dropdown.scss
  public/stylesheets/components/_global.scss
  public/stylesheets/components/_grid.scss
  public/stylesheets/components/_icons-material-design.scss
  public/stylesheets/components/_materialbox.scss
  public/stylesheets/components/_modal.scss
  public/stylesheets/components/_navbar.scss
  public/stylesheets/components/_normalize.scss
  public/stylesheets/components/_preloader.scss
  public/stylesheets/components/_pulse.scss
  public/stylesheets/components/_sidenav.scss
  public/stylesheets/components/_slider.scss
  public/stylesheets/components/_table_of_contents.scss
  public/stylesheets/components/_tabs.scss
  public/stylesheets/components/_tapTarget.scss
  public/stylesheets/components/_timepicker.scss
  public/stylesheets/components/_toast.scss
  public/stylesheets/components/_tooltip.scss
  public/stylesheets/components/_transitions.scss
  public/stylesheets/components/_typography.scss
  public/stylesheets/components/_variables.scss
  public/stylesheets/components/_waves.scss
  public/stylesheets/components/forms/_checkboxes.scss
  public/stylesheets/components/forms/_file-input.scss
  public/stylesheets/components/forms/_forms.scss
  public/stylesheets/components/forms/_input-fields.scss
  public/stylesheets/components/forms/_radio-buttons.scss
  public/stylesheets/components/forms/_range.scss
  public/stylesheets/components/forms/_select.scss
  public/stylesheets/components/forms/_switches.scss
  public/stylesheets/materialize.scss
Labels: API / External, Interface

#13 Imports Materialize javascript components.
  public/javascripts/anime.min.js
  public/javascripts/autocomplete.js
  public/javascripts/bin/materialize.js
  public/javascripts/bin/materialize.min.js
  public/javascripts/buttons.js
  public/javascripts/cards.js
  public/javascripts/carousel.js
  public/javascripts/cash.js
  public/javascripts/characterCounter.js
  public/javascripts/chips.js
  public/javascripts/collapsible.js
  public/javascripts/component.js
  public/javascripts/datepicker.js
  public/javascripts/dropdown.js
  public/javascripts/forms.js
  public/javascripts/global.js
  public/javascripts/materialbox.js
  public/javascripts/modal.js
  public/javascripts/parallax.js
  public/javascripts/pushpin.js
  public/javascripts/range.js
  public/javascripts/scrollspy.js
  public/javascripts/select.js
  public/javascripts/sidenav.js
  public/javascripts/slider.js
  public/javascripts/tabs.js
  public/javascripts/tapTarget.js
  public/javascripts/timepicker.js
  public/javascripts/toasts.js
  public/javascripts/tooltip.js
  public/javascripts/waves.js
Labels: API / External

#14 added dropbox api file fetch
  routes/index.js
  routes/utils.js
Labels: API / External, Backend, Feature

#16 fixed packages
  package.json
Labels: Bug

#18 Adds Jasmine as our testing solution
  package.json
  spec/jasmine_spec.js
  spec/support/jasmine.json
Labels: Tests

#19 Add Dropbox Environment Variable
  routes/utils.js
Labels: API / External, Backend
