Repository CodyMichaelSimmons/EmployeeWellnessProject, pull requests merged in 2018-12, with the labels that each got.

#64 ID3 Frontend Integration
  public/javascripts/main.js
  public/stylesheets/components/_variables.scss
  public/stylesheets/style.sass
  public/stylesheets/utilities/_variables.sass
  views/advanced-settings-tab.pug
  views/decade-form.pug
  views/footer.pug
  views/form-holder.pug
  views/genre-form.pug
  views/getting-started-tab.pug
  views/header.pug
  views/interval-form.pug
Labels: Backend, Feature, Interface

#66 added tests for backend and endpoints
  spec/backend_spec.js
  spec/endpoints_spec.js
Labels: Tests

#68 Version Update
  public/javascripts/main.js
  public/stylesheets/components/_variables.scss
  public/stylesheets/style.sass
  public/stylesheets/utilities/_variables.sass
  spec/backend_spec.js
  spec/endpoints_spec.js
  views/advanced-settings-tab.pug
  views/decade-form.pug
  views/footer.pug
  views/form-holder.pug
  views/genre-form.pug
  views/getting-started-tab.pug
  views/header.pug
  views/interval-form.pug
Labels: API / External, Backend, Feature, Interface, Tests, docs

#69 Added title and artist display
  public/javascripts/main.js
  public/stylesheets/style.sass
  views/home-tab.pug
Labels: Interface

#70 Added filter tests
  spec/filter_spec.js
Labels: Tests

#71 Final fixes
  public/javascripts/main.js
  public/stylesheets/style.sass
  views/decade-form.pug
  views/genre-form.pug
  views/getting-started-tab.pug
  views/header.pug
  views/interval-form.pug
Labels: Interface

#72 Light theme
  public/stylesheets/components/_variables.scss
  public/stylesheets/style.sass
  views/form-holder.pug
  views/home-tab.pug
  views/theme-form.pug
Labels: Interface

#74 Fixed an issue with title display
  public/javascripts/main.js
Labels: Bug

#75 Resolves spacing issues for volume slider.
  public/stylesheets/style.sass
Labels: Interface

#76 Develop
  public/javascripts/main.js
  public/stylesheets/components/_variables.scss
  public/stylesheets/style.sass
  spec/filter_spec.js
  views/decade-form.pug
  views/form-holder.pug
  views/genre-form.pug
  views/getting-started-tab.pug
  views/header.pug
  views/home-tab.pug
  views/interval-form.pug
  views/theme-form.pug
Labels: Bug, Feature, Interface, docs

#77 Updates README.
  README.md
Labels: docs

#78 Develop
  README.md
Labels: docs
